http:
  port: 80
  hostname: 'localhost'
apiEndpoints:
  api-user:
    host: 'localhost'
    paths: [ '/user', /user/*']
  api-chapter:
    host: 'localhost'
    paths: ['/chapter/', /chapter/*']
  api-course:
    host: 'localhost'
    paths: ['/course/', '/course/*']
serviceEndpoints:
  url-users:
    url: 'http://localhost:3000'
  url-courses:
    url: 'http://localhost:3001'
  url-chapters:
    url: 'http://localhost:3002'
policies:
  - cors
  - proxy
pipelines:
  users:
    apiEndpoints: 
      - api-user
    policies:
      - proxy:
          - action:
              serviceEndpoint: url-users
              changeOrigin: true
  courses:
    apiEndpoints: 
      - api-course
    policies:
      - proxy:
          - action:
              serviceEndpoint: url-courses
              changeOrigin: true
  chapters:
    apiEndpoints: 
      - api-chapter
    policies:
      - proxy:
          - action:
              serviceEndpoint: url-chapters
              changeOrigin: true

